# Need more hooks? see https://pre-commit.com/hooks.html

repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--safe]
        language_version: python3.10

#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v2.3.0
#    hooks:
#      - id: check-merge-conflict
#      - id: end-of-file-fixer
#      - id: flake8
#        additional_dependencies: ["flake8-bugbear == 19.3.0"]
#        language_version: python3.8
#      - id: trailing-whitespace

#  - repo: https://github.com/asottile/pyupgrade
#    rev: v1.12.0
#    hooks:
#      - id: pyupgrade
#        args: [--py36-plus]
