name: Formatting and Snippets
on:
  push:
    branches: ['main']
jobs:
  format_and_snippets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run black
      run: |
        ./format_code.sh
    - name: Run MarkdownSnippets
      run: |
        ./run_mdsnippets.sh
      shell: bash
    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: "${secrets.GITHUB_TOKEN}"
        commit-message: ". d format and update markdown snippets"
        rebase: 'true'
        push-branch: 'main'
        name: github actions
        email: actions@github.com 

