name: Python Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pylint action
        uses: gabriel-milan/action-pylint@v1
        with:
          # Path of files
          path: .
          fail: true
          pr-message: false
